<?php

function open_eggheads_research_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'biblio' && $view_mode == 'full') {
    $node->content['links'] = NULL;
    
    // Build the breadcrumbs in the format Home > News > Title Of Post
    $breadcrumb = array();
    $breadcrumb[] = l(t('Research'), 'research');
    $breadcrumb[] = l(drupal_get_title(), request_path()); // Link to current URL
    // Set the breadcrumbs
    drupal_set_breadcrumb($breadcrumb);
  }
}

function open_eggheads_research_page_alter(&$page) {
  if (request_path() == 'research') {
    // Remove export links from display. (Biblio-specific issue)
    $biblio_page_content = &$page['content']['system_main']['biblio_page']['content'];
    foreach ($biblio_page_content as &$value) {
      if (isset($value['0'])) {
        $value['0']['export_links']['#markup'] = NULL;
      }
    }
    unset($value); // break the reference with the last element
    
    // Hide Biblio header.
    $page['content']['system_main']['biblio_page']['header'] = NULL;
    
    // Insert help text for research page.
    $page['content']['#sorted'] = FALSE;
    $page['content']['help_text'] = array(
      '#markup' => t('For more information on a specific piece of research, click on its title.'),
      '#prefix' => '<p class="text-muted"><em>',
      '#suffix' => '</em></p>',
      '#weight' => -999,
    );
  }
}

/**
 * Implements hook_form_FORM_ID_alter. Used to alter the edit form for the Research content type.
 */
function open_eggheads_research_form_biblio_node_form_alter(&$form, &$form_state, $form_id) {
  $form['#attached']['js'][] = array(
    'data' => drupal_get_path('module', 'open_eggheads_research') . '/js/open_eggheads_research_biblio_node_form.js',
    'options' => array(
      'type' => 'file',
      'group' => JS_THEME,
      'weight' => 100,
    ),
  );
  $form['field_biblio_pdf']['und']['#after_build'][] = '_open_eggheads_research_form_biblio_node_form_alter_field';
}

/**
 * after_build functions for PDF Upload field, to reformat the field's label and Browse button.
 */
function _open_eggheads_research_form_biblio_node_form_alter_field($element, &$form_state) {
  $element['0']['#title'] = '<h2>PDF Upload</h2>';
  
  $button_classes = array('btn', 'btn-default', 'btn-primary');
  foreach ($button_classes as $value) {
    $element['0']['browse_button']['#attributes']['class'][] = $value;
  }
  
  return $element;
}
