<?php
/**
 * @file
 * Custom admin pages that allow users to easily edit the site's basic info and appearance.
 * @dependencies:
 * - Radix theme: https://www.drupal.org/project/radix
 * - Radix Colorizer module: https://www.drupal.org/project/radix_colorizer
 */

/**
 * Implements hook_permissions().
 */
 function open_eggheads_admin_interface_permissions() {
   // @todo Set permissions for module.
   // @todo Edit 'access arguments' in open_eggheads_admin_interface_menu() to account for new permissions.
   // @todo Explicitly set 'access callback' to 'user_access' in open_eggheads_admin_interface_menu() for added clarity.
 }

/**
 * Implements hook_menu().
 */
function open_eggheads_admin_interface_menu() {
  $items = array();
  
  $items['admin/open-eggheads'] = array(
    'title' => 'Open Eggheads Dashboard',
    'description' => t('Manage the most important settings for your Open Eggheads website.'),
    'page callback' => '_open_eggheads_admin_interface_dashboard',
    'access arguments' => array('access administration menu'), // User has access to /admin
    'weight' => -100, // Make sure this link appears first in the admin toolbar.
    'file' => 'open_eggheads_admin_interface.dashboard.inc',
    'options' => array(
      'attributes' => array(
        'id' => 'open-eggheads-dashboard-btn',
      ),
    ),
  );
  
  $items['admin/open-eggheads/personal-data'] = array(
    'title' => 'Personal Data',
    'description' => t('Update your personal data for your Open Eggheads website.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('open_eggheads_admin_interface_personal_data_form'),
    'access arguments' => array('access administration menu'), // User has access to /admin
    'file' => 'open_eggheads_admin_interface.personal_data_form.inc',
    'weight' => -100,
  );
  
  $items['admin/open-eggheads/appearance-editor'] = array(
    'title' => 'Appearance Editor',
    'page callback' => '_open_eggheads_admin_interface_appearance_editor_form',
    'access arguments' => array('access administration menu'), // User has access to /admin
    'file' => 'open_eggheads_admin_interface.appearance_editor_form.inc',
    'weight' => -75,
  );
  
  $items['admin/open-eggheads/add-content'] = array(
    'title' => 'Add Content',
    'page callback' => 'drupal_goto',
    'page arguments' => array('node/add'),
    'access arguments' => array('access administration menu'), // User has access to /admin
    'weight' => -50,
  );
  
  $items['admin/open-eggheads/find-content'] = array(
    'title' => 'Find Content',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/content'),
    'access arguments' => array('access administration menu'), // User has access to /admin
    'weight' => -25,
  );
  
  $items['admin/open-eggheads/faq'] = array(
    'title' => 'Frequently Asked Questions',
    'description' => t('Use these questions to help get to know your Open Eggheads site and how to use it.'),
    'page callback' => '_open_eggheads_admin_interface_faq',
    'access arguments' => array('access administration menu'), // User has access to /admin
    'file' => 'open_eggheads_admin_interface.faq.inc',
    'weight' => 0,
  );
  
  return $items;
}

/**
 * Implements hook_page_alter().
 * 
 * @access public
 * @param mixed &$page
 * @return void
 */
function open_eggheads_admin_interface_page_alter(&$page) {
  if (request_path() == 'node/add' || request_path() == 'admin/content') {
    // Build the breadcrumbs in the format Home > News > Title Of Post
    $breadcrumb = array();
    $breadcrumb[] = l(t('Home'), '<front>');
    $breadcrumb[] = l(t('Open Eggheads Dashboard'), 'admin/open-eggheads');
    $breadcrumb[] = l(drupal_get_title(), request_path()); // Link to current URL
    // Set the breadcrumbs
    drupal_set_breadcrumb($breadcrumb);
  }
  
  // For any users who are logged in with admin privileges.
  // Create a Help button that will remain fixed on the upper left corner of the screen.
  // Help button will link to the site's FAQ page.
  if (user_access('access administration menu')) {
    $page['content']['#attached'] = array(
      'js' => array(
        drupal_get_path('module', 'open_eggheads_admin_interface') . '/js/open_eggheads_admin_interface.help_button.js' => array(
          'type' => 'file',
          'group' => JS_THEME,
          'weight' => 100,
        ),
      ),
      'css' => array(
        drupal_get_path('module', 'open_eggheads_admin_interface') . '/css/open_eggheads_admin_interface.help_button.css' => array(
          'type' => 'file',
          'group' => CSS_THEME,
          'weight' => 100,
        ),
      ),
    );
  }
}
